#!/usr/bin/env python3
"""Build src/syscall_names.h: fx-CG syscall number -> name, from libfxcg's sources.

libfxcg (github.com/Jonimoose/libfxcg) implements every OS call as a tiny assembly stub
    mov.l 1f, r2 ; mov.l 2f, r0 ; jmp @r2 ; nop ; 1: .long 0x80020070 ; 2: .long 0x0272
in libfxcg/*.s (or several stubs per file).  We list the repo tree through the GitHub API,
download every .s/.S file, and collect (label, number) pairs.  Syscall numbers are the OS
API and stable across OS versions (3.60/3.80 differ only in handler addresses).

Output: src/syscall_names.h (a sorted C table) + tools/syscalls.json (cache).
Run:    python tools/fetch_syscalls.py          (needs network the first time)
"""
import json, os, re, sys, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, "syscalls.json")
OUT = os.path.join(HERE, "..", "src", "syscall_names.h")
REPO = "Jonimoose/libfxcg"
API = f"https://api.github.com/repos/{REPO}/git/trees/master?recursive=1"
RAW = f"https://raw.githubusercontent.com/{REPO}/master/"

def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": "cg50-dasm/1.0"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()

def collect():
    tree = json.loads(get(API))["tree"]
    files = [t["path"] for t in tree if t["type"] == "blob" and t["path"].lower().endswith((".s", ".S"))]
    print(f"{len(files)} assembly files")
    names = {}
    for i, p in enumerate(files):
        txt = get(RAW + p).decode("utf-8", "replace")
        # stubs look like:  .global _Bdisp_AllClr_VRAM  ...  _Bdisp_AllClr_VRAM: ... .long 0x0272
        # Walk labels in order; each label's syscall number is the last .long before the next label
        # that is not the trampoline address.
        # libfxcg's real format: one macro per stub  ->  SYSCALL(_APP_SYSTEM_DISPLAY, 0x1E0A)
        for mm in re.finditer(r"SYSCALL\(\s*_?([A-Za-z_][A-Za-z0-9_]*)\s*,\s*(0x[0-9A-Fa-f]+|\d+)\s*\)", txt):
            v = int(mm.group(2), 0)
            if v < 0x4000:
                names.setdefault(v, mm.group(1))
        cur = None
        for line in txt.splitlines():
            line = line.split("!")[0].split(";")[0].strip()
            m = re.match(r"^_([A-Za-z_][A-Za-z0-9_]*):", line)
            if m:
                cur = m.group(1)
                continue
            m = re.match(r"^\.long\s+(0x[0-9A-Fa-f]+|\d+)", line)
            if m and cur:
                v = int(m.group(1), 0)
                if v == 0x80020070:
                    continue
                if v < 0x4000:
                    names.setdefault(v, cur)
                    cur = None
        if i % 50 == 0:
            print(f"  {i}/{len(files)} ... {len(names)} syscalls so far")
    return names

def main():
    if os.path.exists(CACHE) and "--refresh" not in sys.argv:
        names = {int(k): v for k, v in json.load(open(CACHE)).items()}
    else:
        names = collect()
        json.dump({str(k): v for k, v in sorted(names.items())}, open(CACHE, "w"), indent=1)
    # A few numbers libfxcg lacks / we verified ourselves (the casio-cg50 emulator's re/syscall.py)
    extra = {0x025F: "Bdisp_PutDisp_DD", 0x0260: "Bdisp_PutDisp_DD_stripe", 0x0270: "Bdisp_SetPoint_VRAM",
             0x0272: "Bdisp_AllClr_VRAM", 0x0921: "Bdisp_PutDispArea_DD", 0x090F: "GetKey",
             0x0EAB: "PutKeyCode", 0x1E50: "memset", 0x1163: "malloc", 0x0E6B: "RTC_GetTicks"}
    # libfxcg is the authority; add one of these extras only when it contradicts nothing
    # (neither its number nor its name is already listed).
    have_names = set(names.values())
    for k, v in extra.items():
        if k not in names and v not in have_names:
            names[k] = v
    # Prizm wiki (prizm.cemetech.net/index.php/Syscalls): more names, same numbering.
    wiki = os.path.join(HERE, "syscalls_wiki.json")
    if os.path.exists(wiki):
        for k, v in json.load(open(wiki)).items():
            k = int(k, 0)
            if k not in names and v not in have_names:
                names[k] = v; have_names.add(v)
    items = sorted(names.items())
    with open(OUT, "w", newline="\n") as f:
        f.write("/* Generated by tools/fetch_syscalls.py from libfxcg - do not edit. */\n")
        f.write("#ifndef SYSCALL_NAMES_H\n#define SYSCALL_NAMES_H\n#include <stdint.h>\n")
        f.write("struct syscall_name { uint16_t num; const char *name; };\n")
        f.write(f"#define SYSCALL_NAME_COUNT {len(items)}\n")
        f.write("static const struct syscall_name syscall_names[SYSCALL_NAME_COUNT] = {\n")
        for k, v in items:
            f.write(f"  {{ 0x{k:04x}, \"{v}\" }},\n")
        f.write("};\n#endif\n")
    print(f"wrote {OUT}: {len(items)} names")

if __name__ == "__main__":
    main()
