"""Generate src/font_aa.h: the anti-aliased listing font for DASM's "large" font mode.

Renders the 95 printable ASCII glyphs of DejaVu Sans Mono (free licence, fetched once into
tools/.cache/) into fixed CW x CH cells with 8-bit coverage, which src/main.c blends into VRAM.
Also writes tools/.cache/font_preview.png (a mock listing) to judge the look
before building.  Run:  python3 tools/make_font.py [size_px]
"""
import os
import sys
import urllib.request
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, ".cache")
TTF = os.path.join(CACHE, "DejaVuSansMono.ttf")
URL = "https://cdn.jsdelivr.net/npm/dejavu-fonts-ttf@2.37.3/ttf/DejaVuSansMono.ttf"
OUT = os.path.join(HERE, "..", "src", "font_aa.h")

CW, CH = 7, 11          # cell: 7 px advance -> 56 columns on the 396 px wide screen
SIZE = float(sys.argv[1]) if len(sys.argv) > 1 else 11.0
BASELINE = 9            # baseline row: 9 rows above it (i/j dots, brackets), 2 below (g, j, p, y)


def glyphs():
    os.makedirs(CACHE, exist_ok=True)
    if not os.path.exists(TTF):
        urllib.request.urlretrieve(URL, TTF)
    font = ImageFont.truetype(TTF, SIZE)
    out = []
    for c in range(0x20, 0x7F):
        im = Image.new("L", (CW, CH), 0)
        # "_" is the only glyph that reaches a 3rd row under the baseline: lift it by one
        base = BASELINE - 1 if chr(c) == "_" else BASELINE
        ImageDraw.Draw(im).text((0, base), chr(c), font=font, fill=255, anchor="ls")
        out.append(bytes(im.getdata()))
    return out


def write_header(gs):
    with open(OUT, "w") as f:
        f.write("/* Generated by tools/make_font.py -- do not edit.\n")
        f.write(f" * DejaVu Sans Mono {SIZE:g} px, glyphs 0x20..0x7e in {CW}x{CH} cells, 8-bit coverage\n")
        f.write(" * (0 = background, 255 = full ink). DejaVu fonts: Bitstream Vera licence + public domain. */\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write(f"#define AA_CW {CW}\n#define AA_CH {CH}\n\n")
        f.write(f"static const uint8_t font_aa[95][{CW * CH}] = {{\n")
        for i, g in enumerate(gs):
            f.write(f"    /* {chr(0x20 + i)!r} */ {{" + ",".join(str(b) for b in g) + "},\n")
        f.write("};\n")


def preview(gs):
    """Mock listing rows at 2x zoom."""
    rows = [("00300000", "2fe6", "mov.l r14,@-r15", ""),
            ("00300008", "d307", "mov.l @(0x1c,pc),r3", "=0x00300034"),
            ("0030000a", "430b", "jsr @r3", "-> 0x00300034"),
            ("0030000c", "6e53", " mov r5,r14", ""),
            ("00300014", "410b", "jsr @r1", "-> Bdisp_AllClr_VRAM"),
            ("00300022", "472b", "jmp @r7", "")]
    cols = [(0xE0, 0xF0, 0x80), (0xA0, 0xB0, 0x60), (0xE0, 0xE0, 0xE0), (0x40, 0xD0, 0x70)]
    bg = (8, 8, 24)
    W, H = 396, 8 + len(rows) * CH
    im = Image.new("RGB", (W, H), bg)
    px = im.load()

    def draw(x, y, s, rgb):
        for ch in s:
            g = gs[(ord(ch) - 0x20) if 0x20 <= ord(ch) < 0x7F else ord("?") - 0x20]
            for r in range(CH):
                for c in range(CW):
                    a = g[r * CW + c] / 255
                    if a and 0 <= x + c < W and 0 <= y + r < H:
                        b = px[x + c, y + r]
                        px[x + c, y + r] = tuple(int(b[k] + (rgb[k] - b[k]) * a) for k in range(3))
            x += CW

    y = 4
    for a, h, m, cm in rows:
        draw(0, y, a, cols[0]); draw(9 * CW, y, h, cols[1]); draw(14 * CW, y, m, cols[2])
        if cm:
            draw(36 * CW, y, ";" + cm, cols[3])
        y += CH
    im = im.resize((W * 2, H * 2), Image.NEAREST)
    p = os.path.join(CACHE, "font_preview.png")
    im.save(p)
    return p


if __name__ == "__main__":
    gs = glyphs()
    write_header(gs)
    print("wrote", os.path.normpath(OUT), f"({len(gs)} glyphs, {CW}x{CH}, size {SIZE:g})")
    print("preview", preview(gs))
